### PR TITLE
(refactor) client asks for old password on password change

### PR DESCRIPTION
**Pull request by csreyes**

### CODE REVIEW

**Comment by nlokare** [comment]
The range of response codes is kind of strange. Can you check for specific response codes and make another commit?

**Comment by csreyes** [comment]
changed it to when status is 201

**Comment by nlokare** [comment]
Ok, sounds good. Curious, why did you have the range? Is this something you need to handle on the server?

**Comment by nlokare** [comment]
@csreyes Hey, looks like there are some conflicts from your most recent commit. I'm not able to merge.

**Comment by csreyes** [comment]
its because on every other response from the server in the 400+ range we replied with the res.text as "wrong password" or "requires old password", but on a 200, the server sends back the whole user object as res.text; the client is using the res.text as the snackbar, so just in case the server responded with a success that wasn't 201, i wanted there to be a success text for the client to use.

**Comment by nlokare** [comment]
Ok, not quite sure I follow but it's all good.

**Pull request closed without merging**
