### PR TITLE
(feat) add Forgot Password to server

### PR DESCRIPTION
**Pull request by dsernst**
Lays out the beginning of the Forgot Password server logic

### CODE REVIEW

**Comment by nlokare** [comment]
This code is terrible, David.

**Comment by dsernst** [comment]
thank u

**Comment by nlokare** [comment]
No, thank you.

**Comment by dsernst** [comment]
gaia provides

**Comment by nlokare** [comment]
Forever and always

**Comment by dsernst** [comment]
```
               ,,ggddY"""Ybbgg,,
          ,agd888b,_ "Y8, ___`""Ybga,
       ,gdP""88888888baa,.""8b    "888g,
     ,dP"     ]888888888P'  "Y     `888Yb,
   ,dP"      ,88888888P"  db,       "8P""Yb,
  ,8"       ,888888888b, d8888a           "8,
 ,8'        d88888888888,88P"' a,          `8,
,8'         88888888888888PP"  ""           `8,
d'          I88888888888P"                   `b
8           `8"88P""Y8P'                      8
8            Y 8[  _ "                        8
8              "Y8d8b  "Y a                   8
8                 `""8d,   __                 8
Y,                    `"8bd888b,             ,P
`8,                     ,d8888888baaa       ,8'
 `8,                    888888888888'      ,8'
  `8a                   "8888888888I      a8'
   `Yba                  `Y8888888P'    adP'
     "Yba                 `888888P'   adY"
       `"Yba,             d8888P" ,adP"'  
          `"Y8baa,      ,d888P,ad8P"'         
               ``""YYba8888P""''         
```

**Pull request merged**
